package hust.soict.hedspi.garbage;

public class GarbageCreator {
    public static void garBageCreators(int n){
        String a = "";

        while (n-- > 0)
            a+= "Tạo một lớp mới GarbageCreator . Tạo \"rác\" nhiều nhất có thể và quan sátkhi bạn chạy một chương trình (nên để chương trình ngừng hoạt động khi có quá nhiều \"rác\").Viết một lớp khác NoGarbage để giải quyết vấn đề.Một số gợi ý:--Đọc một tệp văn bản / nhị phân thành một Chuỗi mà không sử dụng StringBuffer để nối chuỗi (chỉsử dụng + toán tử). Quan sát và chụp màn hình của bạn khi bạn chọn một tệp rất dài--Cải thiện mã bằng cách sử dụng StringBuffer5. Nộp bài tậpBạn phải đặt tất cả công việc của mình, do chính bạn viết, vào một thư mục Lab05 và đẩy nó vàonhánh chủ của kho lưu trữ hợp lệ trước thời hạn đã thông \n" +
                    "Trang 1\n" +
                    "1Lý thuyết và ngôn ngữ hướng đối tượngGiảng viên: NGUYỄN Thị Thu Trang, trangntt@soict.hust.edu.vnTrợ giảng: ĐỖ Minh Hiếu, hieudominh@hotmail.comLab 05: Quản lý bộ nhớ và tổ chức lớp học* Mục tiêu:Trong phòng thí nghiệm này, bạn sẽ thực hành với:• Tạo các gói để quản lý các lớp trong Eclipse• Sử dụng một số gói / lớp phổ biến của Java API, ví dụ như các lớp Wrapper, Math, System• Thực hành quản lý bộ nhớ với String và StringBuffer và các trường hợp khácBạn cần sử dụng dự án mà bạn đã thực hiện với các phòng thí nghiệm trước đó bao gồm cả AimsProject và cáccác dự án.1. Nhập / xuất một dự án--Mở Eclipse--Bạn có thể nhập / xuất một dự án từ / sang một tệp lưu trữ. Ví dụ: nếu bạn muốnnhập từ tệp zip, bạn có thể làm theo các bước sau:+ Mở File-> Import.+ Gõ zip để tìm Tệp lưu trữ nếu bạn đã xuất dưới dạng tệp zip trước đó. Bạn có thể chọnCác dự án hiện có vào Workspace nếu bạn muốn mở một dự án hiện có trong máy tính của mình.Bỏ qua bước này nếu AimsProject đã được mở trong không gian làm việc.--Nhấp Tiếp theo và Duyệt đến một tệp zip hoặc một dự án để mở\n" +
                    "Trang 2\n" +
                    "22. Tổ chức lại các dự án của bạn- Đổi tên dự án, sử dụng các gói và sắp xếp lại tất cả các phòng thí nghiệm và bài tập thực hành từLab01 tính đến thời điểm hiện tại.+ Để đổi tên hoặc di chuyển một mục (tức là một dự án, một lớp, một biến…), hãy nhấp chuột phải vàochọn Refactor-> Rename / Move và làm theo các bước.Hình 1-Tái cấu trúc+ Để tạo gói, nhấp chuột phải vào dự án (hoặc vào menu Tệp) và chọn Mới->Gói. Nhập đường dẫn đầy đủ của gói bao gồm các gói mẹ, được phân tách bằng dấu chấm.- Cấu trúc phòng thí nghiệm của bạn . Ít nhất là ở bên dưới, bạn có thể tạo các gói phụđể tổ chức hiệu quả hơn các lớp học của bạn trong cả hai dự án và tất cả các gói danh sách. Tất cảphòng thí nghiệm thực hành và bài tập của lab01 và lab02 nên được đưa vàogói trong dự án OtherProjects.Đối với CNTT-TT toàn cầu+ AimsProjectbery.soict.globalict.aims.disc.DigitalVideoDiscbery.soict.globalict.aims.order.Orderbery.soict.globalict.aims.Aimsbery.soict.globalict.aims.utils.DateUtilsbery.soict.globalict.aims.utils.MyDatebery.soict.globalict.test.utils.DateTestbery.soict.globalict.test.disc.TestPassingParameter+ Các dự án khácbery.soict.globalict.lab01bery.soict.globalict.lab02Đối với HEDSPI+ AimsProjectbery.soict.hedspi.aims.disc.DigitalVideoDiscbery.soict.hedspi.aims.order.Orderbery.soict.hedspi.aims.Aimsbery.soict.hedspi.aims.utils.DateUtilsbery.soict.hedspi.aims.utils.MyDatebery.soict.hedspi.test.utils.DateTestbery.soict.hedspi.test.disc.TestPassingParameter+ Các dự án khácbery.soict.hedspi.lab01bery.soict.hedspi.lab02\n" +
                    "Trang 3\n" +
                    "3Hình 2-Cấu trúc được đề xuất cho CNTT-TT toàn cầuHình 3-Cấu trúc đề xuất cho HEDSPI3. Tìm kiếm một dvd trong dự án AimsProject :- Trong lớp DigitalVideoDisc , hãy viết phương thức tìm kiếm boolean (String title)phát hiện ra (không phân biệt chữ hoa chữ thường) nếu đĩa tương ứng của đối tượng hiện tại chứatiêu đề . Hãy nhớ rằng nếu tiêu đề có nhiều mã thông báo (ví dụ: \"Harry Potter\"), phương pháp vẫntrả về true nếu đĩa có tiêu đề bao gồm tất cả các mã thông báo (ví dụ: cả hai mã thông báo “Harry” và“Potter”) bất kể thứ tự và khoảng cách của họ (vì vậy đúng với tất cả các tiêu đề bao gồm cả mã thông báo “Harry”và một mã thông báo “Potter” ở bất kỳ vị trí nào trong tiêu đề )- Trong lớp Order , hãy viết một phương thức DigitalVideoDisc getALuckyItem () màchọn ngẫu nhiên (nhớ sử dụng Math.random () ) một mục miễn phí. Hãy nhớ cập nhậtvà thử nghiệm các phương pháp để liệt kê các dvd và tổng chi phí của một đơn đặt hàng (chỉ định may mắn và miễn phí)mục).--Tạo nênDiskTestlớp để kiểm tra các phương thức này trong góiHttp: //www.soict. [gloalict | hedspi] .aims4. Chuỗi , StringBuilder và StringBuffer :--Trong các OtherProjects dự án, tạo ra một gói phần mềm mới hust.soict.globalict.garbagedành cho ICT hoặc boost.soict.hedspi.garbage cho HEDSPI. Chúng tôi làm việc với gói này trong bài tập này.--Tạo một lớp mới ConcatenationInLoops để kiểm tra thời gian xử lý để xây dựngChuỗi sử dụng toán tử + , StringBuffer và StringBuilder . Phần sau củamã là một gợi ý:\n" +
                    "Trang 4\n" +
                    "BốnThông tin thêm về nối chuỗi , vui lòng tham khảo https://redfin.engineering/java-string-nối-mà-cách-là-tốt nhất-8f590a7d22a8 .--Tạo một lớp mới GarbageCreator . Tạo \"rác\" nhiều nhất có thể và quan sátkhi bạn chạy một chương trình (nên để chương trình ngừng hoạt động khi có quá nhiều \"rác\").Viết một lớp khác NoGarbage để giải quyết vấn đề.Một số gợi ý:--Đọc một tệp văn bản / nhị phân thành một Chuỗi mà không sử dụng StringBuffer để nối chuỗi (chỉsử dụng + toán tử). Quan sát và chụp màn hình của bạn khi bạn chọn một tệp rất dài--Cải thiện mã bằng cách sử dụng StringBuffer5. Nộp bài tậpBạn phải đặt tất cả công việc của mình, do chính bạn viết, vào một thư mục Lab05 và đẩy nó vàonhánh chủ của kho lưu trữ hợp lệ trước thời hạn đã thông báo trong lớp.Mỗi học sinh phải tự làm công việc của mình và không cho hoặc nhận viện trợ không được phép.Nếu không, chúng tôi sẽ áp dụng các phương pháp đo lường cực đoan để ngăn chặn gian lận trong lớp.Mỗi học sinh phải tự làm công việc của mình và không cho hoặc nhận viện trợ không được phép.Nếu không, chúng tôi sẽ áp dụng các phương pháp đo lường cực đoan để ngăn chặn gian lận";
    }
}
